add private and public config module

diff --git a/.github/workflows/bundle_analysis.yml b/.github/workflows/bundle_analysis.yml
--- a/.github/workflows/bundle_analysis.yml
+++ b/.github/workflows/bundle_analysis.yml
@@ -17,7 +17,12 @@ jobs:
 
       - name: Read .nvmrc
         id: nvmrc
-        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
+        run: |
+          if [ ! -f .nvmrc ]; then
+            echo "Error: .nvmrc not found!" >&2
+            exit 1
+          fi
+          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
 
       - name: Install pnpm
         uses: pnpm/action-setup@v4
@@ -25,14 +30,16 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"
+          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
           cache: "pnpm"
 
       - name: Install dependencies
         run: pnpm install
 
       - name: Build
-        run: pnpm build
+        env:
+          UNSET_CONFIG: true
+        run: pnpm build --turbo
 
       - name: Analyze bundle
         uses: andrii-maglovanyi/nextjs-bundle-analyzer@v1
